# Generated by Django 6.0.2 on 2026-04-27 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=200)),
                ("icon", models.CharField(default="🏅", max_length=8)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("special", "Special"),
                        ],
                        default="bronze",
                        max_length=8,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeatureResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.CharField(
                        choices=[
                            ("email", "Phishing Ninja"),
                            ("url", "URL Slayer"),
                            ("ai", "Deepfake Detector"),
                        ],
                        max_length=10,
                    ),
                ),
                ("scenario_id", models.CharField(max_length=20)),
                ("segment_id", models.CharField(max_length=20)),
                ("segment_text", models.CharField(max_length=255)),
                ("identified", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.CharField(
                        choices=[
                            ("email", "Phishing Ninja"),
                            ("url", "URL Slayer"),
                            ("ai", "Deepfake Detector"),
                        ],
                        max_length=10,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("correct_verdicts", models.IntegerField(default=0)),
                ("total_scenarios", models.IntegerField(default=0)),
                ("flags_found", models.IntegerField(default=0)),
                ("flags_total", models.IntegerField(default=0)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="GuestPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("display_name", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario_id", models.CharField(max_length=20)),
                ("verdict_correct", models.BooleanField(default=False)),
                ("flags_found", models.IntegerField(default=0)),
                ("flags_total", models.IntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.badge"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
            },
        ),
        migrations.DeleteModel(
            name="GameProgress",
        ),
        migrations.DeleteModel(
            name="Score",
        ),
        migrations.AddField(
            model_name="featureresult",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="game.gamesession",
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_sessions",
                to="game.guestplayer",
            ),
        ),
        migrations.AddField(
            model_name="questionresult",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="game.gamesession",
            ),
        ),
        migrations.AddIndex(
            model_name="featureresult",
            index=models.Index(
                fields=["game", "scenario_id", "segment_id"],
                name="game_featur_game_3e604b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gamesession",
            index=models.Index(
                fields=["game", "-score"], name="game_gamese_game_ebbf42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gamesession",
            index=models.Index(
                fields=["-completed_at"], name="game_gamese_complet_0a3bcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionresult",
            index=models.Index(
                fields=["session", "scenario_id"], name="game_questi_session_855ead_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userbadge",
            unique_together={("user", "badge")},
        ),
    ]
